
###
GET http://localhost:8080/ads/1/comments
Content-Type: application/json
Authorization: Basic mail@mail.ru 123456789

###
POST http://localhost:8080/register
Content-Type: application/json

{
   "username": "user1222@gmail.com",
   "password": "password",
   "firstName":  "asdaddsa",
   "lastName": "asdadasdasd",
   "phone":  "+79998887766"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "mail@mail.ru",
  "password": "123456789"
}

###
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic mail@mail.ru 123456789

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic mail@mail.ru 123456789

###
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic mail@mail.ru 123456789

{
  "id": 1,
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "phone": "+79998887799",
  "image": ""
}

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic mail@mail.ru 12345678

###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic mail@mail.ru 12345678


###
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic mail@mail.ru 12345678

{
  "currentPassword": 123456789,
  "newPassword": "123456789"
}

###
POST http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic mail@mail.ru 123456789

{
  "description": "string",
  "price": 0,
  "title": "string"
}

###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic mail@mail.ru 12345678

###
PATCH http://localhost:8080/users/role?userId=2&role=ADMIN
Authorization: Basic mail@mail.ru 12345678

###
GET http://localhost:8080/ads/search/1
Authorization: Basic mail@mail.ru 12345678
Content-Type: application/json

###
PATCH /users/me/image HTTP/1.1
Host: localhost:8080
Authorization: Basic bWFpbEBtYWlsLnJ1OjEyMzQ1Njc4OQ==
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="/D:/Image/_oiwntLGdMw.jpg"
Content-Type: image/jpeg

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW--








